// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk.proto

package cn.edu.scut.iais.proto;

public final class DetectorProto {
  private DetectorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ObjectDetectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ObjectDetect)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 state_code = 1;</code>
     */
    boolean hasStateCode();
    /**
     * <code>required int32 state_code = 1;</code>
     */
    int getStateCode();

    /**
     * <code>optional int32 object_count = 2;</code>
     */
    boolean hasObjectCount();
    /**
     * <code>optional int32 object_count = 2;</code>
     */
    int getObjectCount();

    /**
     * <code>repeated .Object object_list = 3;</code>
     */
    java.util.List<cn.edu.scut.iais.proto.DetectorProto.Object> 
        getObjectListList();
    /**
     * <code>repeated .Object object_list = 3;</code>
     */
    cn.edu.scut.iais.proto.DetectorProto.Object getObjectList(int index);
    /**
     * <code>repeated .Object object_list = 3;</code>
     */
    int getObjectListCount();
    /**
     * <code>repeated .Object object_list = 3;</code>
     */
    java.util.List<? extends cn.edu.scut.iais.proto.DetectorProto.ObjectOrBuilder> 
        getObjectListOrBuilderList();
    /**
     * <code>repeated .Object object_list = 3;</code>
     */
    cn.edu.scut.iais.proto.DetectorProto.ObjectOrBuilder getObjectListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ObjectDetect}
   */
  public static final class ObjectDetect extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ObjectDetect)
      ObjectDetectOrBuilder {
    // Use ObjectDetect.newBuilder() to construct.
    private ObjectDetect(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ObjectDetect(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ObjectDetect defaultInstance;
    public static ObjectDetect getDefaultInstance() {
      return defaultInstance;
    }

    public ObjectDetect getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ObjectDetect(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              stateCode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              objectCount_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                objectList_ = new java.util.ArrayList<cn.edu.scut.iais.proto.DetectorProto.Object>();
                mutable_bitField0_ |= 0x00000004;
              }
              objectList_.add(input.readMessage(cn.edu.scut.iais.proto.DetectorProto.Object.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          objectList_ = java.util.Collections.unmodifiableList(objectList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.edu.scut.iais.proto.DetectorProto.internal_static_ObjectDetect_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.edu.scut.iais.proto.DetectorProto.internal_static_ObjectDetect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.edu.scut.iais.proto.DetectorProto.ObjectDetect.class, cn.edu.scut.iais.proto.DetectorProto.ObjectDetect.Builder.class);
    }

    public static com.google.protobuf.Parser<ObjectDetect> PARSER =
        new com.google.protobuf.AbstractParser<ObjectDetect>() {
      public ObjectDetect parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ObjectDetect(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ObjectDetect> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STATE_CODE_FIELD_NUMBER = 1;
    private int stateCode_;
    /**
     * <code>required int32 state_code = 1;</code>
     */
    public boolean hasStateCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 state_code = 1;</code>
     */
    public int getStateCode() {
      return stateCode_;
    }

    public static final int OBJECT_COUNT_FIELD_NUMBER = 2;
    private int objectCount_;
    /**
     * <code>optional int32 object_count = 2;</code>
     */
    public boolean hasObjectCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 object_count = 2;</code>
     */
    public int getObjectCount() {
      return objectCount_;
    }

    public static final int OBJECT_LIST_FIELD_NUMBER = 3;
    private java.util.List<cn.edu.scut.iais.proto.DetectorProto.Object> objectList_;
    /**
     * <code>repeated .Object object_list = 3;</code>
     */
    public java.util.List<cn.edu.scut.iais.proto.DetectorProto.Object> getObjectListList() {
      return objectList_;
    }
    /**
     * <code>repeated .Object object_list = 3;</code>
     */
    public java.util.List<? extends cn.edu.scut.iais.proto.DetectorProto.ObjectOrBuilder> 
        getObjectListOrBuilderList() {
      return objectList_;
    }
    /**
     * <code>repeated .Object object_list = 3;</code>
     */
    public int getObjectListCount() {
      return objectList_.size();
    }
    /**
     * <code>repeated .Object object_list = 3;</code>
     */
    public cn.edu.scut.iais.proto.DetectorProto.Object getObjectList(int index) {
      return objectList_.get(index);
    }
    /**
     * <code>repeated .Object object_list = 3;</code>
     */
    public cn.edu.scut.iais.proto.DetectorProto.ObjectOrBuilder getObjectListOrBuilder(
        int index) {
      return objectList_.get(index);
    }

    private void initFields() {
      stateCode_ = 0;
      objectCount_ = 0;
      objectList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStateCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getObjectListCount(); i++) {
        if (!getObjectList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, stateCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, objectCount_);
      }
      for (int i = 0; i < objectList_.size(); i++) {
        output.writeMessage(3, objectList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, stateCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, objectCount_);
      }
      for (int i = 0; i < objectList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, objectList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.edu.scut.iais.proto.DetectorProto.ObjectDetect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.ObjectDetect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.ObjectDetect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.ObjectDetect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.ObjectDetect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.ObjectDetect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.ObjectDetect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.ObjectDetect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.ObjectDetect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.ObjectDetect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.edu.scut.iais.proto.DetectorProto.ObjectDetect prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ObjectDetect}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ObjectDetect)
        cn.edu.scut.iais.proto.DetectorProto.ObjectDetectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.edu.scut.iais.proto.DetectorProto.internal_static_ObjectDetect_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.edu.scut.iais.proto.DetectorProto.internal_static_ObjectDetect_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.edu.scut.iais.proto.DetectorProto.ObjectDetect.class, cn.edu.scut.iais.proto.DetectorProto.ObjectDetect.Builder.class);
      }

      // Construct using cn.edu.scut.iais.proto.DetectorProto.ObjectDetect.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getObjectListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stateCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        objectCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (objectListBuilder_ == null) {
          objectList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          objectListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.edu.scut.iais.proto.DetectorProto.internal_static_ObjectDetect_descriptor;
      }

      public cn.edu.scut.iais.proto.DetectorProto.ObjectDetect getDefaultInstanceForType() {
        return cn.edu.scut.iais.proto.DetectorProto.ObjectDetect.getDefaultInstance();
      }

      public cn.edu.scut.iais.proto.DetectorProto.ObjectDetect build() {
        cn.edu.scut.iais.proto.DetectorProto.ObjectDetect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.edu.scut.iais.proto.DetectorProto.ObjectDetect buildPartial() {
        cn.edu.scut.iais.proto.DetectorProto.ObjectDetect result = new cn.edu.scut.iais.proto.DetectorProto.ObjectDetect(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stateCode_ = stateCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.objectCount_ = objectCount_;
        if (objectListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            objectList_ = java.util.Collections.unmodifiableList(objectList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.objectList_ = objectList_;
        } else {
          result.objectList_ = objectListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.edu.scut.iais.proto.DetectorProto.ObjectDetect) {
          return mergeFrom((cn.edu.scut.iais.proto.DetectorProto.ObjectDetect)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.edu.scut.iais.proto.DetectorProto.ObjectDetect other) {
        if (other == cn.edu.scut.iais.proto.DetectorProto.ObjectDetect.getDefaultInstance()) return this;
        if (other.hasStateCode()) {
          setStateCode(other.getStateCode());
        }
        if (other.hasObjectCount()) {
          setObjectCount(other.getObjectCount());
        }
        if (objectListBuilder_ == null) {
          if (!other.objectList_.isEmpty()) {
            if (objectList_.isEmpty()) {
              objectList_ = other.objectList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureObjectListIsMutable();
              objectList_.addAll(other.objectList_);
            }
            onChanged();
          }
        } else {
          if (!other.objectList_.isEmpty()) {
            if (objectListBuilder_.isEmpty()) {
              objectListBuilder_.dispose();
              objectListBuilder_ = null;
              objectList_ = other.objectList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              objectListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getObjectListFieldBuilder() : null;
            } else {
              objectListBuilder_.addAllMessages(other.objectList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStateCode()) {
          
          return false;
        }
        for (int i = 0; i < getObjectListCount(); i++) {
          if (!getObjectList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.edu.scut.iais.proto.DetectorProto.ObjectDetect parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.edu.scut.iais.proto.DetectorProto.ObjectDetect) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int stateCode_ ;
      /**
       * <code>required int32 state_code = 1;</code>
       */
      public boolean hasStateCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 state_code = 1;</code>
       */
      public int getStateCode() {
        return stateCode_;
      }
      /**
       * <code>required int32 state_code = 1;</code>
       */
      public Builder setStateCode(int value) {
        bitField0_ |= 0x00000001;
        stateCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 state_code = 1;</code>
       */
      public Builder clearStateCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stateCode_ = 0;
        onChanged();
        return this;
      }

      private int objectCount_ ;
      /**
       * <code>optional int32 object_count = 2;</code>
       */
      public boolean hasObjectCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 object_count = 2;</code>
       */
      public int getObjectCount() {
        return objectCount_;
      }
      /**
       * <code>optional int32 object_count = 2;</code>
       */
      public Builder setObjectCount(int value) {
        bitField0_ |= 0x00000002;
        objectCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 object_count = 2;</code>
       */
      public Builder clearObjectCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        objectCount_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<cn.edu.scut.iais.proto.DetectorProto.Object> objectList_ =
        java.util.Collections.emptyList();
      private void ensureObjectListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          objectList_ = new java.util.ArrayList<cn.edu.scut.iais.proto.DetectorProto.Object>(objectList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cn.edu.scut.iais.proto.DetectorProto.Object, cn.edu.scut.iais.proto.DetectorProto.Object.Builder, cn.edu.scut.iais.proto.DetectorProto.ObjectOrBuilder> objectListBuilder_;

      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public java.util.List<cn.edu.scut.iais.proto.DetectorProto.Object> getObjectListList() {
        if (objectListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(objectList_);
        } else {
          return objectListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public int getObjectListCount() {
        if (objectListBuilder_ == null) {
          return objectList_.size();
        } else {
          return objectListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public cn.edu.scut.iais.proto.DetectorProto.Object getObjectList(int index) {
        if (objectListBuilder_ == null) {
          return objectList_.get(index);
        } else {
          return objectListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public Builder setObjectList(
          int index, cn.edu.scut.iais.proto.DetectorProto.Object value) {
        if (objectListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectListIsMutable();
          objectList_.set(index, value);
          onChanged();
        } else {
          objectListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public Builder setObjectList(
          int index, cn.edu.scut.iais.proto.DetectorProto.Object.Builder builderForValue) {
        if (objectListBuilder_ == null) {
          ensureObjectListIsMutable();
          objectList_.set(index, builderForValue.build());
          onChanged();
        } else {
          objectListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public Builder addObjectList(cn.edu.scut.iais.proto.DetectorProto.Object value) {
        if (objectListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectListIsMutable();
          objectList_.add(value);
          onChanged();
        } else {
          objectListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public Builder addObjectList(
          int index, cn.edu.scut.iais.proto.DetectorProto.Object value) {
        if (objectListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectListIsMutable();
          objectList_.add(index, value);
          onChanged();
        } else {
          objectListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public Builder addObjectList(
          cn.edu.scut.iais.proto.DetectorProto.Object.Builder builderForValue) {
        if (objectListBuilder_ == null) {
          ensureObjectListIsMutable();
          objectList_.add(builderForValue.build());
          onChanged();
        } else {
          objectListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public Builder addObjectList(
          int index, cn.edu.scut.iais.proto.DetectorProto.Object.Builder builderForValue) {
        if (objectListBuilder_ == null) {
          ensureObjectListIsMutable();
          objectList_.add(index, builderForValue.build());
          onChanged();
        } else {
          objectListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public Builder addAllObjectList(
          java.lang.Iterable<? extends cn.edu.scut.iais.proto.DetectorProto.Object> values) {
        if (objectListBuilder_ == null) {
          ensureObjectListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, objectList_);
          onChanged();
        } else {
          objectListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public Builder clearObjectList() {
        if (objectListBuilder_ == null) {
          objectList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          objectListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public Builder removeObjectList(int index) {
        if (objectListBuilder_ == null) {
          ensureObjectListIsMutable();
          objectList_.remove(index);
          onChanged();
        } else {
          objectListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public cn.edu.scut.iais.proto.DetectorProto.Object.Builder getObjectListBuilder(
          int index) {
        return getObjectListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public cn.edu.scut.iais.proto.DetectorProto.ObjectOrBuilder getObjectListOrBuilder(
          int index) {
        if (objectListBuilder_ == null) {
          return objectList_.get(index);  } else {
          return objectListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public java.util.List<? extends cn.edu.scut.iais.proto.DetectorProto.ObjectOrBuilder> 
           getObjectListOrBuilderList() {
        if (objectListBuilder_ != null) {
          return objectListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(objectList_);
        }
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public cn.edu.scut.iais.proto.DetectorProto.Object.Builder addObjectListBuilder() {
        return getObjectListFieldBuilder().addBuilder(
            cn.edu.scut.iais.proto.DetectorProto.Object.getDefaultInstance());
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public cn.edu.scut.iais.proto.DetectorProto.Object.Builder addObjectListBuilder(
          int index) {
        return getObjectListFieldBuilder().addBuilder(
            index, cn.edu.scut.iais.proto.DetectorProto.Object.getDefaultInstance());
      }
      /**
       * <code>repeated .Object object_list = 3;</code>
       */
      public java.util.List<cn.edu.scut.iais.proto.DetectorProto.Object.Builder> 
           getObjectListBuilderList() {
        return getObjectListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.edu.scut.iais.proto.DetectorProto.Object, cn.edu.scut.iais.proto.DetectorProto.Object.Builder, cn.edu.scut.iais.proto.DetectorProto.ObjectOrBuilder> 
          getObjectListFieldBuilder() {
        if (objectListBuilder_ == null) {
          objectListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cn.edu.scut.iais.proto.DetectorProto.Object, cn.edu.scut.iais.proto.DetectorProto.Object.Builder, cn.edu.scut.iais.proto.DetectorProto.ObjectOrBuilder>(
                  objectList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          objectList_ = null;
        }
        return objectListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ObjectDetect)
    }

    static {
      defaultInstance = new ObjectDetect(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ObjectDetect)
  }

  public interface ObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Object)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 object_id = 1;</code>
     */
    boolean hasObjectId();
    /**
     * <code>required int32 object_id = 1;</code>
     */
    int getObjectId();

    /**
     * <code>required float score = 2;</code>
     */
    boolean hasScore();
    /**
     * <code>required float score = 2;</code>
     */
    float getScore();

    /**
     * <code>required int32 x = 3;</code>
     */
    boolean hasX();
    /**
     * <code>required int32 x = 3;</code>
     */
    int getX();

    /**
     * <code>required int32 y = 4;</code>
     */
    boolean hasY();
    /**
     * <code>required int32 y = 4;</code>
     */
    int getY();

    /**
     * <code>required int32 w = 5;</code>
     */
    boolean hasW();
    /**
     * <code>required int32 w = 5;</code>
     */
    int getW();

    /**
     * <code>required int32 h = 6;</code>
     */
    boolean hasH();
    /**
     * <code>required int32 h = 6;</code>
     */
    int getH();
  }
  /**
   * Protobuf type {@code Object}
   */
  public static final class Object extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Object)
      ObjectOrBuilder {
    // Use Object.newBuilder() to construct.
    private Object(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Object(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Object defaultInstance;
    public static Object getDefaultInstance() {
      return defaultInstance;
    }

    public Object getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Object(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              objectId_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              score_ = input.readFloat();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              x_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              y_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              w_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              h_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.edu.scut.iais.proto.DetectorProto.internal_static_Object_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.edu.scut.iais.proto.DetectorProto.internal_static_Object_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.edu.scut.iais.proto.DetectorProto.Object.class, cn.edu.scut.iais.proto.DetectorProto.Object.Builder.class);
    }

    public static com.google.protobuf.Parser<Object> PARSER =
        new com.google.protobuf.AbstractParser<Object>() {
      public Object parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Object(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Object> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int OBJECT_ID_FIELD_NUMBER = 1;
    private int objectId_;
    /**
     * <code>required int32 object_id = 1;</code>
     */
    public boolean hasObjectId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 object_id = 1;</code>
     */
    public int getObjectId() {
      return objectId_;
    }

    public static final int SCORE_FIELD_NUMBER = 2;
    private float score_;
    /**
     * <code>required float score = 2;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float score = 2;</code>
     */
    public float getScore() {
      return score_;
    }

    public static final int X_FIELD_NUMBER = 3;
    private int x_;
    /**
     * <code>required int32 x = 3;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 x = 3;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 4;
    private int y_;
    /**
     * <code>required int32 y = 4;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 y = 4;</code>
     */
    public int getY() {
      return y_;
    }

    public static final int W_FIELD_NUMBER = 5;
    private int w_;
    /**
     * <code>required int32 w = 5;</code>
     */
    public boolean hasW() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 w = 5;</code>
     */
    public int getW() {
      return w_;
    }

    public static final int H_FIELD_NUMBER = 6;
    private int h_;
    /**
     * <code>required int32 h = 6;</code>
     */
    public boolean hasH() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 h = 6;</code>
     */
    public int getH() {
      return h_;
    }

    private void initFields() {
      objectId_ = 0;
      score_ = 0F;
      x_ = 0;
      y_ = 0;
      w_ = 0;
      h_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasObjectId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasW()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasH()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, objectId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, score_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, y_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, w_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, h_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, objectId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, score_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, y_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, w_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, h_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.edu.scut.iais.proto.DetectorProto.Object parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.Object parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.Object parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.Object parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.Object parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.Object parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.Object parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.Object parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.Object parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.Object parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.edu.scut.iais.proto.DetectorProto.Object prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Object}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Object)
        cn.edu.scut.iais.proto.DetectorProto.ObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.edu.scut.iais.proto.DetectorProto.internal_static_Object_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.edu.scut.iais.proto.DetectorProto.internal_static_Object_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.edu.scut.iais.proto.DetectorProto.Object.class, cn.edu.scut.iais.proto.DetectorProto.Object.Builder.class);
      }

      // Construct using cn.edu.scut.iais.proto.DetectorProto.Object.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        objectId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        w_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        h_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.edu.scut.iais.proto.DetectorProto.internal_static_Object_descriptor;
      }

      public cn.edu.scut.iais.proto.DetectorProto.Object getDefaultInstanceForType() {
        return cn.edu.scut.iais.proto.DetectorProto.Object.getDefaultInstance();
      }

      public cn.edu.scut.iais.proto.DetectorProto.Object build() {
        cn.edu.scut.iais.proto.DetectorProto.Object result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.edu.scut.iais.proto.DetectorProto.Object buildPartial() {
        cn.edu.scut.iais.proto.DetectorProto.Object result = new cn.edu.scut.iais.proto.DetectorProto.Object(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.objectId_ = objectId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.score_ = score_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.w_ = w_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.h_ = h_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.edu.scut.iais.proto.DetectorProto.Object) {
          return mergeFrom((cn.edu.scut.iais.proto.DetectorProto.Object)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.edu.scut.iais.proto.DetectorProto.Object other) {
        if (other == cn.edu.scut.iais.proto.DetectorProto.Object.getDefaultInstance()) return this;
        if (other.hasObjectId()) {
          setObjectId(other.getObjectId());
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasW()) {
          setW(other.getW());
        }
        if (other.hasH()) {
          setH(other.getH());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasObjectId()) {
          
          return false;
        }
        if (!hasScore()) {
          
          return false;
        }
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasW()) {
          
          return false;
        }
        if (!hasH()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.edu.scut.iais.proto.DetectorProto.Object parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.edu.scut.iais.proto.DetectorProto.Object) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int objectId_ ;
      /**
       * <code>required int32 object_id = 1;</code>
       */
      public boolean hasObjectId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 object_id = 1;</code>
       */
      public int getObjectId() {
        return objectId_;
      }
      /**
       * <code>required int32 object_id = 1;</code>
       */
      public Builder setObjectId(int value) {
        bitField0_ |= 0x00000001;
        objectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 object_id = 1;</code>
       */
      public Builder clearObjectId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        objectId_ = 0;
        onChanged();
        return this;
      }

      private float score_ ;
      /**
       * <code>required float score = 2;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float score = 2;</code>
       */
      public float getScore() {
        return score_;
      }
      /**
       * <code>required float score = 2;</code>
       */
      public Builder setScore(float value) {
        bitField0_ |= 0x00000002;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float score = 2;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = 0F;
        onChanged();
        return this;
      }

      private int x_ ;
      /**
       * <code>required int32 x = 3;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 x = 3;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required int32 x = 3;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000004;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 x = 3;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>required int32 y = 4;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 y = 4;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>required int32 y = 4;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000008;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 y = 4;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000008);
        y_ = 0;
        onChanged();
        return this;
      }

      private int w_ ;
      /**
       * <code>required int32 w = 5;</code>
       */
      public boolean hasW() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 w = 5;</code>
       */
      public int getW() {
        return w_;
      }
      /**
       * <code>required int32 w = 5;</code>
       */
      public Builder setW(int value) {
        bitField0_ |= 0x00000010;
        w_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 w = 5;</code>
       */
      public Builder clearW() {
        bitField0_ = (bitField0_ & ~0x00000010);
        w_ = 0;
        onChanged();
        return this;
      }

      private int h_ ;
      /**
       * <code>required int32 h = 6;</code>
       */
      public boolean hasH() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 h = 6;</code>
       */
      public int getH() {
        return h_;
      }
      /**
       * <code>required int32 h = 6;</code>
       */
      public Builder setH(int value) {
        bitField0_ |= 0x00000020;
        h_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 h = 6;</code>
       */
      public Builder clearH() {
        bitField0_ = (bitField0_ & ~0x00000020);
        h_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Object)
    }

    static {
      defaultInstance = new Object(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Object)
  }

  public interface SceneDetectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SceneDetect)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 state_code = 1;</code>
     */
    boolean hasStateCode();
    /**
     * <code>required int32 state_code = 1;</code>
     */
    int getStateCode();

    /**
     * <code>optional int32 scene_id = 2;</code>
     */
    boolean hasSceneId();
    /**
     * <code>optional int32 scene_id = 2;</code>
     */
    int getSceneId();

    /**
     * <code>optional float score = 3;</code>
     */
    boolean hasScore();
    /**
     * <code>optional float score = 3;</code>
     */
    float getScore();
  }
  /**
   * Protobuf type {@code SceneDetect}
   */
  public static final class SceneDetect extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SceneDetect)
      SceneDetectOrBuilder {
    // Use SceneDetect.newBuilder() to construct.
    private SceneDetect(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SceneDetect(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SceneDetect defaultInstance;
    public static SceneDetect getDefaultInstance() {
      return defaultInstance;
    }

    public SceneDetect getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SceneDetect(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              stateCode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sceneId_ = input.readInt32();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              score_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.edu.scut.iais.proto.DetectorProto.internal_static_SceneDetect_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.edu.scut.iais.proto.DetectorProto.internal_static_SceneDetect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.edu.scut.iais.proto.DetectorProto.SceneDetect.class, cn.edu.scut.iais.proto.DetectorProto.SceneDetect.Builder.class);
    }

    public static com.google.protobuf.Parser<SceneDetect> PARSER =
        new com.google.protobuf.AbstractParser<SceneDetect>() {
      public SceneDetect parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SceneDetect(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SceneDetect> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STATE_CODE_FIELD_NUMBER = 1;
    private int stateCode_;
    /**
     * <code>required int32 state_code = 1;</code>
     */
    public boolean hasStateCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 state_code = 1;</code>
     */
    public int getStateCode() {
      return stateCode_;
    }

    public static final int SCENE_ID_FIELD_NUMBER = 2;
    private int sceneId_;
    /**
     * <code>optional int32 scene_id = 2;</code>
     */
    public boolean hasSceneId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 scene_id = 2;</code>
     */
    public int getSceneId() {
      return sceneId_;
    }

    public static final int SCORE_FIELD_NUMBER = 3;
    private float score_;
    /**
     * <code>optional float score = 3;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float score = 3;</code>
     */
    public float getScore() {
      return score_;
    }

    private void initFields() {
      stateCode_ = 0;
      sceneId_ = 0;
      score_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStateCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, stateCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sceneId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, score_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, stateCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sceneId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, score_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.edu.scut.iais.proto.DetectorProto.SceneDetect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.SceneDetect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.SceneDetect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.SceneDetect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.SceneDetect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.SceneDetect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.SceneDetect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.SceneDetect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.SceneDetect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.edu.scut.iais.proto.DetectorProto.SceneDetect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.edu.scut.iais.proto.DetectorProto.SceneDetect prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SceneDetect}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SceneDetect)
        cn.edu.scut.iais.proto.DetectorProto.SceneDetectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.edu.scut.iais.proto.DetectorProto.internal_static_SceneDetect_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.edu.scut.iais.proto.DetectorProto.internal_static_SceneDetect_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.edu.scut.iais.proto.DetectorProto.SceneDetect.class, cn.edu.scut.iais.proto.DetectorProto.SceneDetect.Builder.class);
      }

      // Construct using cn.edu.scut.iais.proto.DetectorProto.SceneDetect.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stateCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sceneId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.edu.scut.iais.proto.DetectorProto.internal_static_SceneDetect_descriptor;
      }

      public cn.edu.scut.iais.proto.DetectorProto.SceneDetect getDefaultInstanceForType() {
        return cn.edu.scut.iais.proto.DetectorProto.SceneDetect.getDefaultInstance();
      }

      public cn.edu.scut.iais.proto.DetectorProto.SceneDetect build() {
        cn.edu.scut.iais.proto.DetectorProto.SceneDetect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.edu.scut.iais.proto.DetectorProto.SceneDetect buildPartial() {
        cn.edu.scut.iais.proto.DetectorProto.SceneDetect result = new cn.edu.scut.iais.proto.DetectorProto.SceneDetect(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stateCode_ = stateCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sceneId_ = sceneId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.score_ = score_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.edu.scut.iais.proto.DetectorProto.SceneDetect) {
          return mergeFrom((cn.edu.scut.iais.proto.DetectorProto.SceneDetect)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.edu.scut.iais.proto.DetectorProto.SceneDetect other) {
        if (other == cn.edu.scut.iais.proto.DetectorProto.SceneDetect.getDefaultInstance()) return this;
        if (other.hasStateCode()) {
          setStateCode(other.getStateCode());
        }
        if (other.hasSceneId()) {
          setSceneId(other.getSceneId());
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStateCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.edu.scut.iais.proto.DetectorProto.SceneDetect parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.edu.scut.iais.proto.DetectorProto.SceneDetect) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int stateCode_ ;
      /**
       * <code>required int32 state_code = 1;</code>
       */
      public boolean hasStateCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 state_code = 1;</code>
       */
      public int getStateCode() {
        return stateCode_;
      }
      /**
       * <code>required int32 state_code = 1;</code>
       */
      public Builder setStateCode(int value) {
        bitField0_ |= 0x00000001;
        stateCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 state_code = 1;</code>
       */
      public Builder clearStateCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stateCode_ = 0;
        onChanged();
        return this;
      }

      private int sceneId_ ;
      /**
       * <code>optional int32 scene_id = 2;</code>
       */
      public boolean hasSceneId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 scene_id = 2;</code>
       */
      public int getSceneId() {
        return sceneId_;
      }
      /**
       * <code>optional int32 scene_id = 2;</code>
       */
      public Builder setSceneId(int value) {
        bitField0_ |= 0x00000002;
        sceneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 scene_id = 2;</code>
       */
      public Builder clearSceneId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sceneId_ = 0;
        onChanged();
        return this;
      }

      private float score_ ;
      /**
       * <code>optional float score = 3;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float score = 3;</code>
       */
      public float getScore() {
        return score_;
      }
      /**
       * <code>optional float score = 3;</code>
       */
      public Builder setScore(float value) {
        bitField0_ |= 0x00000004;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float score = 3;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000004);
        score_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SceneDetect)
    }

    static {
      defaultInstance = new SceneDetect(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SceneDetect)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ObjectDetect_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ObjectDetect_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Object_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Object_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SceneDetect_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SceneDetect_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tsdk.proto\"V\n\014ObjectDetect\022\022\n\nstate_cod" +
      "e\030\001 \002(\005\022\024\n\014object_count\030\002 \001(\005\022\034\n\013object_" +
      "list\030\003 \003(\0132\007.Object\"V\n\006Object\022\021\n\tobject_" +
      "id\030\001 \002(\005\022\r\n\005score\030\002 \002(\002\022\t\n\001x\030\003 \002(\005\022\t\n\001y\030" +
      "\004 \002(\005\022\t\n\001w\030\005 \002(\005\022\t\n\001h\030\006 \002(\005\"B\n\013SceneDete" +
      "ct\022\022\n\nstate_code\030\001 \002(\005\022\020\n\010scene_id\030\002 \001(\005" +
      "\022\r\n\005score\030\003 \001(\002B\'\n\026cn.edu.scut.iais.prot" +
      "oB\rDetectorProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ObjectDetect_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ObjectDetect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ObjectDetect_descriptor,
        new java.lang.String[] { "StateCode", "ObjectCount", "ObjectList", });
    internal_static_Object_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Object_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Object_descriptor,
        new java.lang.String[] { "ObjectId", "Score", "X", "Y", "W", "H", });
    internal_static_SceneDetect_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SceneDetect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SceneDetect_descriptor,
        new java.lang.String[] { "StateCode", "SceneId", "Score", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
