/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zoson_detection_jni_DetectorJni */

#ifndef _Included_com_zoson_detection_jni_DetectorJni
#define _Included_com_zoson_detection_jni_DetectorJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zoson_detection_jni_DetectorJni
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zoson_detection_jni_DetectorJni_init
  (JNIEnv *, jobject);

/*
 * Class:     com_zoson_detection_jni_DetectorJni
 * Method:    deInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zoson_detection_jni_DetectorJni_deInit
  (JNIEnv *, jobject);

/*
 * Class:     com_zoson_detection_jni_DetectorJni
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zoson_detection_jni_DetectorJni_run
  (JNIEnv *, jobject);

/*
 * Class:     com_zoson_detection_jni_DetectorJni
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zoson_detection_jni_DetectorJni_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
