/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zoson_detection_jni_JniInterface */

#ifndef _Included_com_zoson_detection_jni_JniInterface
#define _Included_com_zoson_detection_jni_JniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zoson_detection_jni_JniInterface
 * Method:    newContext
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_zoson_detection_jni_JniInterface_newContext
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_zoson_detection_jni_JniInterface
 * Method:    newDetector
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_zoson_detection_jni_JniInterface_newDetector
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_zoson_detection_jni_JniInterface
 * Method:    getDetector
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_zoson_detection_jni_JniInterface_getDetector
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_zoson_detection_jni_JniInterface
 * Method:    initJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zoson_detection_jni_JniInterface_initJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zoson_detection_jni_JniInterface
 * Method:    deInitJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zoson_detection_jni_JniInterface_deInitJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zoson_detection_jni_JniInterface
 * Method:    doDetectJni
 * Signature: (J[BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_zoson_detection_jni_JniInterface_doDetectJni
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
